---
- name: Deploy Weblink20EAR
  hosts: qadmgr
  user: a420018
  become: yes
  become_method: sudo
  become_user: wasadmin

  vars:
     Weblink20EAR_version: 2.11_2.11.0.5 
##     ibm_webservicesclient_bnd_xmi: /opt/wasprofiles/Dmgr01/config/cells/qa-dmgr01Cell01/applications/PAOServiceWAS85EAR.ear/deployments/PAOServiceWAS85EAR-edition{{ PAOServiceWAS85EAR_version }}/PAOServiceProjectWAS85.jar/META-INF/ibm-webservicesclient-bnd.xmi

  vars_prompt:
#  - name: username
#    prompt: "Username for wsadmin.sh"
#    private: no
#  - name: password
#    prompt: "Password for wsadmin.sh"

  tasks:
  - name: copy both .ear file & jython scripts to remote
    copy:
      src: "{{ item }}"
      dest: ~/larrytest/ 
      force: yes 
      mode: 0744
    with_items:
      - /cygdrive/c/backup/gpi_deploy/PAO/Weblink2_EAR_{{ Weblink20EAR_version }}.ear
      - ./py/deployWeblink20EAR_QA.py
      - ./sh/deployWeblink20EAR_QA.sh
      - ./sh/incl/dmgr_addto_soap_client_props.sh
      - ./sh/incl/dmgr_remfrom_soap_client_props.sh
      - ./xslt/modify_Weblink20EAR_ibm_webservicesclient_bnd_xmi_QA.xsl

  - name: include variable file
    include_vars: yml/vars/allvars.yml



  - name: run shell script
    shell: ~/larrytest/deployWeblink20EAR_QA.sh "{{username}}" "{{password}}" "{{Weblink20EAR_version}}"
    register: output
  - debug:
       var=output.stdout_lines



