---
- name: Deploy PAOServiceWAS85EAR 
  hosts: devdmgr
  user: a420018
  become: yes
  become_method: sudo
  become_user: wasadmin
  vars:
    PAOServiceWAS85EAR_version: PAO_2_17.2.17.0.5
    ibm_webservicesclient_bnd_xmi: /opt/wasprofiles/Dmgr01/config/cells/dev-dmgr01Cell01/applications/PAOServiceWAS85EAR.ear/deployments/PAOServiceWAS85EAR-edition{{ PAOServiceWAS85EAR_version }}/PAOServiceProjectWAS85.jar/META-INF/ibm-webservicesclient-bnd.xmi
  vars_prompt:
#  - name: username
#    prompt: "Username for wsadmin.sh"
#    private: no
#  - name: password
#    prompt: "Password for wsadmin.sh"

  tasks:
  - name: copy both .ear file & jython scripts to remote
    copy:
      src: "{{ item }}"
      dest: ~/larrytest/ 
      force: yes 
      mode: 0744
    with_items:
      - /cygdrive/c/backup/gpi_deploy/PAO/PAOServiceWAS85EAR_{{ PAOServiceWAS85EAR_version }}.ear
      - ./py/deployPAOServiceWAS85EAR_Dev.py
      - ./sh/deployPAOServiceWAS85EAR_Dev.sh
      - ./sh/incl/dmgr_addto_soap_client_props.sh
      - ./sh/incl/dmgr_remfrom_soap_client_props.sh
      - ./xslt/modify_ibm_webservicesclient_bnd_xmi_Dev.xsl

  - name: include variable file
    include_vars: yml/vars/allvars.yml

  - name: run shell script
    shell: ~/larrytest/deployPAOServiceWAS85EAR_Dev.sh "{{username}}" "{{password}}" "{{PAOServiceWAS85EAR_version}}"
    register: output
  - debug:
       var=output.stdout_lines

  - name: run xsltproc.sh script
    shell: "xsltproc ~/larrytest/modify_ibm_webservicesclient_bnd_xmi_Dev.xsl {{ ibm_webservicesclient_bnd_xmi }} > /tmp/ibm-webservicesclient-bnd.xmi"
    register: output
  - debug:
       var=output.stdout_lines

  - name: backup ibm-webservicesclient-bnd.xmi
    command: mv /opt/wasprofiles/Dmgr01/config/cells/dev-dmgr01Cell01/applications/PAOServiceWAS85EAR.ear/deployments/PAOServiceWAS85EAR-edition{{ PAOServiceWAS85EAR_version }}/PAOServiceProjectWAS85.jar/META-INF/ibm-webservicesclient-bnd.xmi /opt/wasprofiles/Dmgr01/config/cells/dev-dmgr01Cell01/applications/PAOServiceWAS85EAR.ear/deployments/PAOServiceWAS85EAR-edition{{ PAOServiceWAS85EAR_version }}/PAOServiceProjectWAS85.jar/META-INF/ibm-webservicesclient-bnd.xmi_backup
    register: output
  - debug:
       var=output.stdout_lines

  - name: move new ibm-webservicesclient-bnd.xmi
    command: mv /tmp/ibm-webservicesclient-bnd.xmi /opt/wasprofiles/Dmgr01/config/cells/dev-dmgr01Cell01/applications/PAOServiceWAS85EAR.ear/deployments/PAOServiceWAS85EAR-edition{{ PAOServiceWAS85EAR_version }}/PAOServiceProjectWAS85.jar/META-INF/
    register: output
  - debug:
       var=output.stdout_lines


