- name: simple
  hosts: devdmgr
  user: a420018
  become: yes
  become_method: sudo
  become_user: wasadmin

  vars_prompt:
#  - name: username
#    prompt: "Username for wsadmin.sh"
#    private: no
#  - name: password
#    prompt: "Password for wsadmin.sh"

  tasks:
  - name: copy both .ear file & jython scripts to remote
    copy:
      src: "{{ item }}"
      dest: ~/larrytest/ 
      force: yes 
      mode: 0444
    with_items:
      - ./sh/startDmgrDev.sh

  - name: include variable file
    include_vars: yml/vars/allvars.yml

  - name: run shell script
    shell: chmod 700 ~/larrytest/startDmgrDev.sh;~/larrytest/startDmgrDev.sh
    register: output
  - debug:
       var=output.stdout_lines





#  - name: run xsltproc.sh script
#    shell: "xsltproc ~/src3.xsl ~/src3.xml > /tmp/out3.xml"

#  - name: move /tmp/out3.xml to /home/wasadmin/
#    command: mv /tmp/out3.xml /home/wasadmin/


